@Api_HostAddress = http://localhost:1338

###

POST {{Api_HostAddress}}/catalog/912e6d7b-e1f7-48a2-a86d-8ecebd2bde2c/issues
Content-Type: application/json

{

  "description": "Thing Doesn't Work"
}

### 
GET {{Api_HostAddress}}/catalog/912e6d7b-e1f7-48a2-a86d-8ecebd2bde2c/issues/afc4e39a-4b28-4ea3-b06d-0b57cd6adadb